# Generated by Django 4.0.1 on 2022-01-11 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('barcode', models.BinaryField()),
                ('update_date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.price')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.type')),
            ],
        ),
    ]
